// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLdatabase;

namespace SQLdatabase.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220207230728_CountriesSeeded")]
    partial class CountriesSeeded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Common.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AreaCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int?>("countryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("countryId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Common.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Continent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Continent = "Europe",
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 2,
                            Continent = "Europe",
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Continent = "Oceania",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 4,
                            Continent = "Africa",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 5,
                            Continent = "Europe",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 6,
                            Continent = "Europe",
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 7,
                            Continent = "Africa",
                            Name = "Ivory Coast"
                        },
                        new
                        {
                            Id = 8,
                            Continent = "Asia",
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 9,
                            Continent = "Asia",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 10,
                            Continent = "Africa",
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 11,
                            Continent = "Europe",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 12,
                            Continent = "South America",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 13,
                            Continent = "Europe",
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 14,
                            Continent = "Europe",
                            Name = "Guernsey"
                        },
                        new
                        {
                            Id = 15,
                            Continent = "North America",
                            Name = "United States Virgin Islands"
                        },
                        new
                        {
                            Id = 16,
                            Continent = "Africa",
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 17,
                            Continent = "Europe",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 18,
                            Continent = "Africa",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 19,
                            Continent = "Asia",
                            Name = "South Korea"
                        },
                        new
                        {
                            Id = 20,
                            Continent = "North America",
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 21,
                            Continent = "Europe",
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 22,
                            Continent = "Europe",
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 23,
                            Continent = "North America",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 24,
                            Continent = "Africa",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Id = 25,
                            Continent = "Europe",
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 26,
                            Continent = "South America",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 27,
                            Continent = "Europe",
                            Name = "Jersey"
                        },
                        new
                        {
                            Id = 28,
                            Continent = "Asia",
                            Name = "Laos"
                        },
                        new
                        {
                            Id = 29,
                            Continent = "Asia",
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 30,
                            Continent = "North America",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 31,
                            Continent = "Antarctica",
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            Id = 32,
                            Continent = "Europe",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 33,
                            Continent = "Europe",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Id = 34,
                            Continent = "North America",
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 35,
                            Continent = "Asia",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 36,
                            Continent = "North America",
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 37,
                            Continent = "Asia",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 38,
                            Continent = "North America",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Id = 39,
                            Continent = "Africa",
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 40,
                            Continent = "Asia",
                            Name = "India"
                        },
                        new
                        {
                            Id = 41,
                            Continent = "Africa",
                            Name = "São Tomé and Príncipe"
                        },
                        new
                        {
                            Id = 42,
                            Continent = "Europe",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Id = 43,
                            Continent = "Europe",
                            Name = "Czechia"
                        },
                        new
                        {
                            Id = 44,
                            Continent = "North America",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Id = 45,
                            Continent = "Antarctica",
                            Name = "South Georgia"
                        },
                        new
                        {
                            Id = 46,
                            Continent = "Europe",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 47,
                            Continent = "Africa",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 48,
                            Continent = "North America",
                            Name = "Greenland"
                        },
                        new
                        {
                            Id = 49,
                            Continent = "Oceania",
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 50,
                            Continent = "North America",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 51,
                            Continent = "Oceania",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Id = 52,
                            Continent = "Africa",
                            Name = "Republic of the Congo"
                        },
                        new
                        {
                            Id = 53,
                            Continent = "Asia",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 54,
                            Continent = "Asia",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 55,
                            Continent = "Oceania",
                            Name = "Guam"
                        },
                        new
                        {
                            Id = 56,
                            Continent = "Europe",
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 57,
                            Continent = "Oceania",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 58,
                            Continent = "North America",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Id = 59,
                            Continent = "Africa",
                            Name = "South Sudan"
                        },
                        new
                        {
                            Id = 60,
                            Continent = "North America",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 61,
                            Continent = "Europe",
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 62,
                            Continent = "Africa",
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 63,
                            Continent = "Oceania",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Id = 64,
                            Continent = "North America",
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 65,
                            Continent = "Oceania",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 66,
                            Continent = "South America",
                            Name = "French Guiana"
                        },
                        new
                        {
                            Id = 67,
                            Continent = "Europe",
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 68,
                            Continent = "Europe",
                            Name = "Kosovo"
                        },
                        new
                        {
                            Id = 69,
                            Continent = "Africa",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 70,
                            Continent = "North America",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Id = 71,
                            Continent = "Oceania",
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 72,
                            Continent = "Asia",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 73,
                            Continent = "Africa",
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 74,
                            Continent = "Africa",
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 75,
                            Continent = "Africa",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 76,
                            Continent = "Asia",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 77,
                            Continent = "Asia",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 78,
                            Continent = "Oceania",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Id = 79,
                            Continent = "Oceania",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 80,
                            Continent = "Africa",
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 81,
                            Continent = "Africa",
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 82,
                            Continent = "Asia",
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 83,
                            Continent = "Oceania",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Id = 84,
                            Continent = "Europe",
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 85,
                            Continent = "Africa",
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 86,
                            Continent = "Asia",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 87,
                            Continent = "Europe",
                            Name = "North Macedonia"
                        },
                        new
                        {
                            Id = 88,
                            Continent = "Africa",
                            Name = "Tanzania"
                        },
                        new
                        {
                            Id = 89,
                            Continent = "Africa",
                            Name = "Eswatini"
                        },
                        new
                        {
                            Id = 90,
                            Continent = "Africa",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 91,
                            Continent = "South America",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 92,
                            Continent = "Oceania",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 93,
                            Continent = "Asia",
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 94,
                            Continent = "Africa",
                            Name = "Réunion"
                        },
                        new
                        {
                            Id = 95,
                            Continent = "Europe",
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 96,
                            Continent = "Africa",
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 97,
                            Continent = "Asia",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 98,
                            Continent = "Oceania",
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 99,
                            Continent = "South America",
                            Name = "Falkland Islands"
                        },
                        new
                        {
                            Id = 100,
                            Continent = "Africa",
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 101,
                            Continent = "Asia",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 102,
                            Continent = "North America",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 103,
                            Continent = "North America",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 104,
                            Continent = "Europe",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 105,
                            Continent = "Europe",
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 106,
                            Continent = "Africa",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 107,
                            Continent = "Africa",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 108,
                            Continent = "North America",
                            Name = "Martinique"
                        },
                        new
                        {
                            Id = 109,
                            Continent = "Africa",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = 110,
                            Continent = "North America",
                            Name = "Aruba"
                        },
                        new
                        {
                            Id = 111,
                            Continent = "Oceania",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Id = 112,
                            Continent = "Africa",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 113,
                            Continent = "Asia",
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Id = 114,
                            Continent = "Europe",
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 115,
                            Continent = "Asia",
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 116,
                            Continent = "Oceania",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Id = 117,
                            Continent = "Africa",
                            Name = "Zimbabwe"
                        },
                        new
                        {
                            Id = 118,
                            Continent = "Africa",
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 119,
                            Continent = "Africa",
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 120,
                            Continent = "Oceania",
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            Id = 121,
                            Continent = "Asia",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 122,
                            Continent = "Asia",
                            Name = "Macau"
                        },
                        new
                        {
                            Id = 123,
                            Continent = "Asia",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 124,
                            Continent = "Africa",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 125,
                            Continent = "Europe",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Id = 126,
                            Continent = "Europe",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Id = 127,
                            Continent = "Asia",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 128,
                            Continent = "Europe",
                            Name = "Åland Islands"
                        },
                        new
                        {
                            Id = 129,
                            Continent = "North America",
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 130,
                            Continent = "North America",
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 131,
                            Continent = "North America",
                            Name = "Caribbean Netherlands"
                        },
                        new
                        {
                            Id = 132,
                            Continent = "Oceania",
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 133,
                            Continent = "North America",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 134,
                            Continent = "North America",
                            Name = "Saint Barthélemy"
                        },
                        new
                        {
                            Id = 135,
                            Continent = "Africa",
                            Name = "DR Congo"
                        },
                        new
                        {
                            Id = 136,
                            Continent = "Europe",
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 137,
                            Continent = "South America",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 138,
                            Continent = "Europe",
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 139,
                            Continent = "North America",
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 140,
                            Continent = "Africa",
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 141,
                            Continent = "Asia",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Id = 142,
                            Continent = "Africa",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 143,
                            Continent = "Africa",
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 144,
                            Continent = "North America",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Id = 145,
                            Continent = "Europe",
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 146,
                            Continent = "Africa",
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 147,
                            Continent = "Asia",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 148,
                            Continent = "Oceania",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 149,
                            Continent = "Asia",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 150,
                            Continent = "Oceania",
                            Name = "Pitcairn Islands"
                        },
                        new
                        {
                            Id = 151,
                            Continent = "Africa",
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 152,
                            Continent = "Asia",
                            Name = "Palestine"
                        },
                        new
                        {
                            Id = 153,
                            Continent = "Africa",
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 154,
                            Continent = "North America",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Id = 155,
                            Continent = "North America",
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 156,
                            Continent = "Oceania",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 157,
                            Continent = "Europe",
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 158,
                            Continent = "South America",
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 159,
                            Continent = "Africa",
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 160,
                            Continent = "Asia",
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 161,
                            Continent = "Europe",
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 162,
                            Continent = "Asia",
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 163,
                            Continent = "Europe",
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 164,
                            Continent = "Africa",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Id = 165,
                            Continent = "Asia",
                            Name = "North Korea"
                        },
                        new
                        {
                            Id = 166,
                            Continent = "North America",
                            Name = "British Virgin Islands"
                        },
                        new
                        {
                            Id = 167,
                            Continent = "Africa",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 168,
                            Continent = "Oceania",
                            Name = "Micronesia"
                        },
                        new
                        {
                            Id = 169,
                            Continent = "Europe",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 170,
                            Continent = "South America",
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 171,
                            Continent = "Africa",
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 172,
                            Continent = "Africa",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 173,
                            Continent = "Europe",
                            Name = "France"
                        },
                        new
                        {
                            Id = 174,
                            Continent = "Europe",
                            Name = "Moldova"
                        },
                        new
                        {
                            Id = 175,
                            Continent = "Asia",
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 176,
                            Continent = "Asia",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 177,
                            Continent = "Asia",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 178,
                            Continent = "South America",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 179,
                            Continent = "Europe",
                            Name = "Vatican City"
                        },
                        new
                        {
                            Id = 180,
                            Continent = "Africa",
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 181,
                            Continent = "Europe",
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 182,
                            Continent = "Asia",
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 183,
                            Continent = "Asia",
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 184,
                            Continent = "Africa",
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 185,
                            Continent = "North America",
                            Name = "Curaçao"
                        },
                        new
                        {
                            Id = 186,
                            Continent = "Europe",
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 187,
                            Continent = "Europe",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 188,
                            Continent = "South America",
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 189,
                            Continent = "North America",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Id = 190,
                            Continent = "Africa",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 191,
                            Continent = "Europe",
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 192,
                            Continent = "North America",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 193,
                            Continent = "South America",
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 194,
                            Continent = "Europe",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 195,
                            Continent = "Antarctica",
                            Name = "Heard Island and McDonald Islands"
                        },
                        new
                        {
                            Id = 196,
                            Continent = "North America",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 197,
                            Continent = "Africa",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 198,
                            Continent = "Asia",
                            Name = "Brunei"
                        },
                        new
                        {
                            Id = 199,
                            Continent = "Africa",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 200,
                            Continent = "Africa",
                            Name = "Saint Helena, Ascension and Tristan da Cunha"
                        },
                        new
                        {
                            Id = 201,
                            Continent = "Asia",
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 202,
                            Continent = "South America",
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 203,
                            Continent = "Europe",
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 204,
                            Continent = "Europe",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Id = 205,
                            Continent = "Antarctica",
                            Name = "French Southern and Antarctic Lands"
                        },
                        new
                        {
                            Id = 206,
                            Continent = "Asia",
                            Name = "China"
                        },
                        new
                        {
                            Id = 207,
                            Continent = "Asia",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 208,
                            Continent = "Africa",
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 209,
                            Continent = "Asia",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Id = 210,
                            Continent = "Africa",
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 211,
                            Continent = "South America",
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 212,
                            Continent = "Asia",
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 213,
                            Continent = "Europe",
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 214,
                            Continent = "North America",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Id = 215,
                            Continent = "Asia",
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 216,
                            Continent = "Asia",
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 217,
                            Continent = "Africa",
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 218,
                            Continent = "Europe",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 219,
                            Continent = "Africa",
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 220,
                            Continent = "Oceania",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Id = 221,
                            Continent = "Europe",
                            Name = "Russia"
                        },
                        new
                        {
                            Id = 222,
                            Continent = "North America",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Id = 223,
                            Continent = "Asia",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 224,
                            Continent = "Antarctica",
                            Name = "Antarctica"
                        },
                        new
                        {
                            Id = 225,
                            Continent = "North America",
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 226,
                            Continent = "North America",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 227,
                            Continent = "North America",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 228,
                            Continent = "Asia",
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 229,
                            Continent = "Asia",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 230,
                            Continent = "Europe",
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 231,
                            Continent = "Asia",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 232,
                            Continent = "North America",
                            Name = "Saint Martin"
                        },
                        new
                        {
                            Id = 233,
                            Continent = "Africa",
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 234,
                            Continent = "Europe",
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 235,
                            Continent = "Oceania",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Id = 236,
                            Continent = "North America",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 237,
                            Continent = "Oceania",
                            Name = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            Id = 238,
                            Continent = "Oceania",
                            Name = "Niue"
                        },
                        new
                        {
                            Id = 239,
                            Continent = "Oceania",
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 240,
                            Continent = "Asia",
                            Name = "Vietnam"
                        },
                        new
                        {
                            Id = 241,
                            Continent = "Africa",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 242,
                            Continent = "Oceania",
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 243,
                            Continent = "North America",
                            Name = "Sint Maarten"
                        },
                        new
                        {
                            Id = 244,
                            Continent = "North America",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 245,
                            Continent = "Asia",
                            Name = "Taiwan"
                        },
                        new
                        {
                            Id = 246,
                            Continent = "Asia",
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 247,
                            Continent = "South America",
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 248,
                            Continent = "Africa",
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 249,
                            Continent = "Europe",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 250,
                            Continent = "Asia",
                            Name = "Christmas Island"
                        });
                });

            modelBuilder.Entity("Common.TotalCases", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CountryId");

                    b.ToTable("TotalCases");
                });

            modelBuilder.Entity("Common.City", b =>
                {
                    b.HasOne("Common.Country", "country")
                        .WithMany("Cities")
                        .HasForeignKey("countryId");

                    b.Navigation("country");
                });

            modelBuilder.Entity("Common.TotalCases", b =>
                {
                    b.HasOne("Common.City", null)
                        .WithMany("covidCasesPerDay")
                        .HasForeignKey("CityId");

                    b.HasOne("Common.Country", null)
                        .WithMany("covidCasesPerDay")
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("Common.City", b =>
                {
                    b.Navigation("covidCasesPerDay");
                });

            modelBuilder.Entity("Common.Country", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("covidCasesPerDay");
                });
#pragma warning restore 612, 618
        }
    }
}
